server {
	gzip on;
	gzip_min_length 1k;
	gzip_buffers 4 16k;
	gzip_comp_level 2;
	gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png image/x-icon;
	gzip_vary off;
	gzip_disable "MSIE [1-6]\.";
	client_max_body_size 1m;
	add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; worker-src 'self' blob:; frame-src 'none'; manifest-src 'self'" always;
	add_header X-Content-Type-Options "nosniff" always;
	add_header Referrer-Policy "strict-origin-when-cross-origin" always;
	add_header Permissions-Policy "camera=(), geolocation=(), microphone=(), payment=(), usb=()" always;
	listen  8080;
	root    /app/dist;
	index   index.html;

	location /api/ {
		rewrite		/api/(.*) /$1 break;
		proxy_pass	http://localhost:8000/;
	}
}
